### PR TITLE
Convert to seconds before passing... seconds

### PR DESCRIPTION
**Pull request by sethvargo**
Potentially fix GH-30

### CODE REVIEW

**Comment by sethvargo** [comment]
@chris-rock can you try this change out?

**Comment by chris-rock** [comment]
@sethvargo Now it works like a charm, thank you!

**Comment by sethvargo** [comment]
Fun fact - we're in the middle of rolling out a proper error message for that. It's been failing the whole time, you just happen to hit the error before our nightlies did 😄 . Thanks!

**Comment by chris-rock** [comment]
I always try to stay cutting edge :-) Since I have not said it before, great work on this project Seth.

**Pull request merged**
